version: '3.8'

services:
    python-flask:
      container_name: python-flask
      image: python-flask:0.0.1
      build: 
        context: ./python-flask
        target: debug
        args:
          author: 'Marcio'
      volumes:
        - ./python-flask/src:/src/
      ports:
        - 5000:5000
        - 5678:5678